CREATE TABLE IF NOT EXISTS `bpm_modify_request` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `process_instance_id` varchar(64) NOT NULL COMMENT '主流程实例 ID',
  `process_definition_id` varchar(64) NOT NULL COMMENT '主流程定义 ID',
  `task_id` varchar(64) NOT NULL COMMENT '申请时当前任务 ID',
  `task_definition_key` varchar(255) NOT NULL COMMENT '申请时当前节点 Key',
  `applicant_user_id` bigint NOT NULL COMMENT '申请人用户 ID',
  `accept_user_id` bigint DEFAULT NULL COMMENT '接受人用户 ID',
  `child_process_definition_key` varchar(255) NOT NULL COMMENT '修改子流程定义 Key',
  `child_process_instance_id` varchar(64) DEFAULT NULL COMMENT '修改子流程实例 ID',
  `parent_child_link_id` bigint DEFAULT NULL COMMENT '主子流程关联 ID',
  `reason_type` tinyint DEFAULT NULL COMMENT '原因分类',
  `reason_detail` varchar(1000) NOT NULL COMMENT '原因说明',
  `modify_payload_json` text COMMENT '修改参数 JSON',
  `status` tinyint NOT NULL COMMENT '状态：1 待接受，2 已拒绝，3 修改中，4 已完成，5 已取消',
  `accept_reason` varchar(1000) DEFAULT NULL COMMENT '接受说明',
  `reject_reason` varchar(1000) DEFAULT NULL COMMENT '拒绝说明',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_bpm_modify_request_instance` (`process_instance_id`, `status`, `deleted`),
  KEY `idx_bpm_modify_request_task` (`task_id`, `status`, `deleted`),
  KEY `idx_bpm_modify_request_child` (`child_process_instance_id`, `deleted`),
  KEY `idx_bpm_modify_request_link` (`parent_child_link_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='流程修改申请表';
